<h1>Booster - agg</h1>

In [1]:
import pandas as pd
from sklearn import metrics, svm
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.svm import SVC

In [2]:
import warnings
import numpy as np

# Suppress overflow warning
warnings.filterwarnings("ignore", category=RuntimeWarning)
np.seterr(over='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [3]:
df_normalized = pd.read_csv('booster_normalized.csv')
df_not_normalized = pd.read_csv('booster_not_normalized.csv')

In [4]:
df_normalized.head(5)

,Age,Gender,Education,Income,Pregnant,PatientContact,Occupation,CovidPatientCare,EmploymentYears,PreExistingCondition,...,Location_Pulau Pinang,Location_Sabah,Location_Selangor,Location_Terengganu,A_mean,B_mean,C_mean,D_mean,E_mean,AgreeSubsequentBooster
0,0.912281,1,2,1,0,1,1,1,0.742857,0,...,0,0,0,0,1.0,2.000000,1.000000,1.8,2.6,1
1,0.614035,0,4,2,0,1,1,1,0.285714,0,...,0,0,0,0,0.0,1.666667,0.000000,1.2,4.0,1
2,1.000000,1,2,2,0,0,0,0,0.942857,1,...,0,0,0,0,1.6,1.916667,1.142857,1.8,2.0,0
3,0.824561,1,2,1,0,1,1,1,0.628571,0,...,0,0,0,0,2.0,2.166667,2.142857,2.0,2.2,0
4,0.929825,1,2,2,0,1,1,1,0.742857,0,...,0,0,0,0,0.4,1.500000,0.000000,1.4,2.6,0

In [5]:
df_not_normalized.head(5)

,Age,Gender,Education,Income,Pregnant,PatientContact,Occupation,CovidPatientCare,EmploymentYears,PreExistingCondition,...,Location_Pulau Pinang,Location_Sabah,Location_Selangor,Location_Terengganu,A_mean,B_mean,C_mean,D_mean,E_mean,AgreeSubsequentBooster
0,52,1,2,1,0,1,1,1,26.0,0,...,0,0,0,0,1.0,2.000000,1.000000,1.8,2.6,1
1,35,0,4,2,0,1,1,1,10.0,0,...,0,0,0,0,0.0,1.666667,0.000000,1.2,4.0,1
2,57,1,2,2,0,0,0,0,33.0,1,...,0,0,0,0,1.6,1.916667,1.142857,1.8,2.0,0
3,47,1,2,1,0,1,1,1,22.0,0,...,0,0,0,0,2.0,2.166667,2.142857,2.0,2.2,0
4,53,1,2,2,0,1,1,1,26.0,0,...,0,0,0,0,0.4,1.500000,0.000000,1.4,2.6,0

In [5]:
target_normalized = df_normalized['AgreeSubsequentBooster']

target_not_normalized = df_not_normalized['AgreeSubsequentBooster']

features_normalized = df_normalized.drop('AgreeSubsequentBooster', axis=1)

features_not_normalized = df_not_normalized.drop('AgreeSubsequentBooster', axis=1)

In [7]:
print(target_normalized.value_counts())

AgreeSubsequentBooster
1    113
0     86
Name: count, dtype: int64

In [6]:
x_train_normalized, x_test_normalized, y_train_normalized, y_test_normalized = train_test_split(features_normalized, target_normalized, test_size=0.2, random_state=0)

x_train_not_normalized, x_test_not_normalized, y_train_not_normalized, y_test_not_normalized = train_test_split(features_not_normalized, target_not_normalized, test_size=0.2, random_state=0)

<h2>KNN</h2>

KNN normalized

In [9]:
def knn_normalized():
    
    max_accuracy = 0
    max_x = 1


    for x in range(1, 31):

        clf = KNeighborsClassifier(n_neighbors=x)

        scores = cross_val_score(clf, x_train_normalized, y_train_normalized,
                                 cv=5, scoring='accuracy')
        score_mean = scores.mean()
        if score_mean > max_accuracy:
            max_accuracy = score_mean
            max_x = x
        
    print("Best accuracy is ", max_accuracy, " at p = ", max_x)

knn_normalized()

Best accuracy is  0.7169354838709678  at p =  10

In [10]:
# Train the model using the entire training set with the best k
knn_best = KNeighborsClassifier(n_neighbors=10)
knn_best.fit(x_train_normalized, y_train_normalized)

KNeighborsClassifier(n_neighbors=10)

In [11]:
# Predict the target for the test dataset
test_predict = knn_best.predict(x_test_normalized)

test_predict

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0])

In [12]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.575

KNN not normalized

In [13]:
def knn_not_normalized():

    max_accuracy = 0
    max_x = 1


    for x in range(1, 31):

        clf = KNeighborsClassifier(n_neighbors=x)

        scores = cross_val_score(clf, x_train_not_normalized, y_train_not_normalized,
                                 cv=5, scoring='accuracy')
        score_mean = scores.mean()
        if score_mean > max_accuracy:
            max_accuracy = score_mean
            max_x = x

    print("Best accuracy is ", max_accuracy, " at p = ", max_x)
    return max_x

best_p = knn_not_normalized()

Best accuracy is  0.6854838709677419  at p =  3

In [14]:
# Train the model using the entire training set with the best k
knn_best = KNeighborsClassifier(n_neighbors=best_p)
knn_best.fit(x_train_not_normalized, y_train_not_normalized)

KNeighborsClassifier(n_neighbors=3)

In [15]:
# Predict the target for the test dataset
test_predict = knn_best.predict(x_test_not_normalized)

test_predict

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0])

In [16]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_not_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.6

<h2>Decision tree</h2>

Decision tree normalized

In [17]:
from sklearn.tree import DecisionTreeClassifier


def dt(x_train, y_train):

    # Initialize lists to store depth values and validation scores
    D = []
    validation = []
    scores = {}
    
    # The for loop will test depth values from 3 to 22
    for d in range(3, 23):
        clf = DecisionTreeClassifier(criterion='entropy', max_depth=d, random_state=0)
    
        # Perform cross-validation and compute the mean accuracy
        cv_scores = cross_val_score(clf, x_train, y_train, cv=5, scoring='accuracy')
        validation_score = cv_scores.mean()
    
        # Store depth value and corresponding validation score
        D.append(d)
        validation.append(validation_score)
        scores[d] = validation_score
    
    # Find the best depth
    best_depth = max(scores, key=scores.get)
    print(f"The best depth is {best_depth} with a validation score of {scores[best_depth]}")
    
    return best_depth


best_depth = dt(x_train_normalized, y_train_normalized)

The best depth is 4 with a validation score of 0.6848790322580645

In [18]:
# Train the model using the entire training set with the best depth
dtree_best = DecisionTreeClassifier(criterion='entropy', max_depth=best_depth, random_state=0)
dtree_best.fit(x_train_normalized, y_train_normalized)

DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=0)

In [19]:
# Predict the target for the test dataset
test_predict = dtree_best.predict(x_test_normalized)

test_predict

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0])

In [20]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.65

decision tree not normalized

In [21]:
best_depth = dt(x_train_not_normalized, y_train_not_normalized)

The best depth is 4 with a validation score of 0.6848790322580645

In [22]:
# Train the model using the entire training set with the best depth
dtree_best = DecisionTreeClassifier(criterion='entropy', max_depth=best_depth, random_state=0)
dtree_best.fit(x_train_not_normalized, y_train_not_normalized)

DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=0)

In [23]:
# Predict the target for the test dataset
test_predict = dtree_best.predict(x_test_not_normalized)

test_predict

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0])

In [24]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_not_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.6

<h2>GNB</h2>

GNB normalized

In [25]:
def gnb_normalized():

    current_model = GaussianNB()
    
    current_model.fit(x_train_normalized, y_train_normalized)
    y_pred = current_model.predict(x_test_normalized)

    acc = metrics.accuracy_score(y_test_normalized, y_pred)
    print("Accuracy (Test):", acc)
        
gnb_normalized()

Accuracy (Test): 0.375

GNB not normalized

In [26]:
def gnb_not_normalized():

    current_model = GaussianNB()
        
    current_model.fit(x_train_not_normalized, y_train_not_normalized)
    test_predict = current_model.predict(x_test_not_normalized)
    print("Accuracy (Test): ", metrics.accuracy_score(y_test_not_normalized, test_predict))
    
gnb_not_normalized()

Accuracy (Test):  0.4

<h2>MNB</h2>

mnb normalized

In [27]:
mnb = MultinomialNB()

scores = cross_val_score(mnb, x_train_normalized, y_train_normalized, cv = 10, scoring="accuracy")
print("Accuracy (Validation) =", scores.mean())
mnb.fit(x_train_normalized, y_train_normalized)
test_predict = mnb.predict(x_test_normalized)
print("Accuracy (Test): ", metrics.accuracy_score(y_test_normalized, test_predict))

Accuracy (Validation) = 0.6729166666666667
Accuracy (Test):  0.675

MNB not normalized

In [28]:
def mnb_not_normalized():
    
    mnb = MultinomialNB()
    
    scores = cross_val_score(mnb, x_train_not_normalized, y_train_not_normalized, cv = 10, scoring="accuracy")
    print("Accuracy (Validation) =", scores.mean())
    mnb.fit(x_train_not_normalized, y_train_not_normalized)
    test_predict = mnb.predict(x_test_not_normalized)
    print("Accuracy (Test): ", metrics.accuracy_score(y_test_not_normalized, test_predict))
    
mnb_not_normalized()

Accuracy (Validation) = 0.6425
Accuracy (Test):  0.5

<h2>MLP - 1 layer</h2>

MLP 1 layer normalized

In [8]:
# Import necessary libraries
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier

# Function to perform cross-validation and find the best hidden layer size
def find_best_hidden_layer_size(hidden_layer_sizes, x_train, y_train):
    best_score = 0
    best_size = None
    for size in hidden_layer_sizes:
        mlp = MLPClassifier(hidden_layer_sizes=size, max_iter=3000, random_state=42)
        scores = cross_val_score(mlp, x_train, y_train, cv=5, scoring='accuracy')
        mean_score = scores.mean()
        print(f'Hidden layer size {size}: Mean cross-validation accuracy = {mean_score}')
        if mean_score > best_score:
            best_score = mean_score
            best_size = size
    return best_size, best_score

# Define hidden layer sizes to test
hidden_layer_sizes_1 = [(h,) for h in [5] + list(range(10, 101, 5))]
hidden_layer_sizes_2 = [(5, h) for h in [5] + list(range(10, 101, 5))]

# Find the best hidden layer size for 1 hidden layer
best_size_1, best_score_1 = find_best_hidden_layer_size(hidden_layer_sizes_1, x_train_normalized, y_train_normalized)
print(f'Best hidden layer size for 1 layer: {best_size_1} with score {best_score_1}')

MLP 1 layer not normalized

In [ ]:
# # Find the best hidden layer size for 1 hidden layer
# best_size_1, best_score_1 = find_best_hidden_layer_size(hidden_layer_sizes_1, x_train_not_normalized, y_train_not_normalized)
# print(f'Best hidden layer size for 1 layer: {best_size_1} with score {best_score_1}')

Hidden layer size (5,): Mean cross-validation accuracy = 0.6919354838709678
Hidden layer size (10,): Mean cross-validation accuracy = 0.6788306451612903
Hidden layer size (15,): Mean cross-validation accuracy = 0.6473790322580645
Hidden layer size (20,): Mean cross-validation accuracy = 0.6352822580645161
Hidden layer size (25,): Mean cross-validation accuracy = 0.5844758064516129
Hidden layer size (30,): Mean cross-validation accuracy = 0.6665322580645161
Hidden layer size (35,): Mean cross-validation accuracy = 0.6725806451612903
Hidden layer size (40,): Mean cross-validation accuracy = 0.6790322580645161
Hidden layer size (45,): Mean cross-validation accuracy = 0.6788306451612903
Hidden layer size (50,): Mean cross-validation accuracy = 0.6598790322580645

/opt/anaconda3/envs/code/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:792: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")

Hidden layer size (55,): Mean cross-validation accuracy = 0.6288306451612903
Hidden layer size (60,): Mean cross-validation accuracy = 0.6848790322580645
Hidden layer size (65,): Mean cross-validation accuracy = 0.5788306451612903

/opt/anaconda3/envs/code/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:792: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")

<h2>MLP - 2 layer</h2>

MLP 2 layer normalized

In [9]:
# Find the best hidden layer size for 2 hidden layers
best_size_2, best_score_2 = find_best_hidden_layer_size(hidden_layer_sizes_2, x_train_normalized, y_train_normalized)
print(f'Best hidden layer size for 2 layers: {best_size_2} with score {best_score_2}')

Hidden layer size (5, 5): Mean cross-validation accuracy = 0.6727822580645161
Hidden layer size (5, 10): Mean cross-validation accuracy = 0.6219758064516129
Hidden layer size (5, 15): Mean cross-validation accuracy = 0.6225806451612903
Hidden layer size (5, 20): Mean cross-validation accuracy = 0.6534274193548387
Hidden layer size (5, 25): Mean cross-validation accuracy = 0.6471774193548387
Hidden layer size (5, 30): Mean cross-validation accuracy = 0.6850806451612903
Hidden layer size (5, 35): Mean cross-validation accuracy = 0.6856854838709678
Hidden layer size (5, 40): Mean cross-validation accuracy = 0.7042338709677419
Hidden layer size (5, 45): Mean cross-validation accuracy = 0.6217741935483871
Hidden layer size (5, 50): Mean cross-validation accuracy = 0.6409274193548387
Hidden layer size (5, 55): Mean cross-validation accuracy = 0.6413306451612903
Hidden layer size (5, 60): Mean cross-validation accuracy = 0.6598790322580645
Hidden layer size (5, 65): Mean cross-validation accuracy = 0.666733870967742
Hidden layer size (5, 70): Mean cross-validation accuracy = 0.6606854838709678
Hidden layer size (5, 75): Mean cross-validation accuracy = 0.6348790322580645
Hidden layer size (5, 80): Mean cross-validation accuracy = 0.6407258064516129
Hidden layer size (5, 85): Mean cross-validation accuracy = 0.6538306451612903
Hidden layer size (5, 90): Mean cross-validation accuracy = 0.6284274193548387
Hidden layer size (5, 95): Mean cross-validation accuracy = 0.571975806451613
Hidden layer size (5, 100): Mean cross-validation accuracy = 0.5915322580645161
Best hidden layer size for 2 layers: (5, 40) with score 0.7042338709677419

MLP 2 layer not normalized

In [ ]:
# Find the best hidden layer size for 2 hidden layers
best_size_2, best_score_2 = find_best_hidden_layer_size(hidden_layer_sizes_2, x_train_not_normalized, y_train_not_normalized)
print(f'Best hidden layer size for 2 layers: {best_size_2} with score {best_score_2}')

<h2>SVM (linear)</h2>

SVM normalized

In [10]:
from sklearn.model_selection import GridSearchCV

# Define the parameter range for C
C_range = [0.1,1,10,100]
degree = [2,3,4]

param_grid_linear = {'C': C_range}

# Function to perform Grid Search and evaluate the model for linear kernel
def evaluate_linear_kernel(x_train, y_train, x_test, y_test):
    print("Evaluating linear kernel")
    grid_search = GridSearchCV(SVC(kernel='linear'), param_grid_linear, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for linear kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for linear kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel    
evaluate_linear_kernel(x_train_normalized, y_train_normalized, x_test_normalized, y_test_normalized)

Evaluating linear kernel
Best parameters for linear kernel: {'C': 0.1}
Accuracy (Test) for linear kernel: 0.65
[[ 9  4]
 [10 17]]
              precision    recall  f1-score   support

           0       0.47      0.69      0.56        13
           1       0.81      0.63      0.71        27

    accuracy                           0.65        40
   macro avg       0.64      0.66      0.64        40
weighted avg       0.70      0.65      0.66        40


============================================================

SVM not normalized

In [ ]:
C_range = [0.01,0.1,1,10,100]

param_grid_linear = {'C': C_range}

def evaluate_linear_kernel():

    estimator = SVC(kernel='linear') 
    param_grid = param_grid_linear

    grid_search = GridSearchCV(estimator, param_grid, cv=10, scoring='accuracy')
    grid_result = grid_search.fit(x_train_not_normalized, y_train_not_normalized)

    print(f"Best parameters for {type(estimator).__name__}: {grid_result.best_params_}")

    best_model = grid_result.best_estimator_

    test_predict = best_model.predict(x_test_not_normalized)

    accuracy = metrics.accuracy_score(y_test_not_normalized, test_predict)
    print(f"Accuracy (Test) for best model: {accuracy:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test_not_normalized, test_predict))
    print("\nClassification Report:")
    print(classification_report(y_test_not_normalized, test_predict))
    print("\n" + "="*60 + "\n")

    return accuracy
  
evaluate_linear_kernel()

<h2>SVM (polynomial)</h2>

SVM Polynomial normalized

In [12]:
degree = [2,3,4]
# Define parameter grids for polynomial kernel
param_grid_poly = {'C': [0.1,1,10,100], 'degree': degree, 'gamma': ['scale', 'auto']}

# Function to perform Grid Search and evaluate the model for polynomial kernel
def evaluate_poly_kernel(x_train, y_train, x_test, y_test):

    base_model = SVC(kernel="poly")
        
    print("Evaluating polynomial kernel")
    grid_search = GridSearchCV(base_model, param_grid_poly, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for polynomial kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for polynomial kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel  
evaluate_poly_kernel(x_train=x_train_normalized, y_train=y_train_normalized, x_test=x_test_normalized, y_test=y_test_normalized)

Evaluating polynomial kernel
Best parameters for polynomial kernel: {'C': 1, 'degree': 3, 'gamma': 'auto'}
Accuracy (Test) for polynomial kernel: 0.675
[[ 8  5]
 [ 8 19]]
              precision    recall  f1-score   support

           0       0.50      0.62      0.55        13
           1       0.79      0.70      0.75        27

    accuracy                           0.68        40
   macro avg       0.65      0.66      0.65        40
weighted avg       0.70      0.68      0.68        40


============================================================

SVM polynomial not normalized

In [ ]:
#print the best evaluate linear kernel  
evaluate_poly_kernel(x_train=x_train_not_normalized, y_train=y_train_not_normalized, x_test=x_test_not_normalized, y_test=y_test_not_normalized)

<h2>SVM (sigmoid)</h2>

svm sigmoid normalized

In [14]:
# Define parameter grids for sigmoid kernel
param_grid_sigmoid = {'C': C_range, 'gamma': ['scale', 'auto']}

# Function to perform Grid Search and evaluate the model for sigmoid kernel
def evaluate_sigmoid_kernel(x_train, y_train, x_test, y_test):
    
    base_model = SVC(kernel="sigmoid")
        
    print("Evaluating sigmoid kernel")
    grid_search = GridSearchCV(base_model, param_grid_sigmoid, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for sigmoid kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for sigmoid kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel  
evaluate_sigmoid_kernel(x_train=x_train_normalized, x_test=x_test_normalized, y_train=y_train_normalized, y_test=y_test_normalized)

Evaluating sigmoid kernel
Best parameters for sigmoid kernel: {'C': 10, 'gamma': 'auto'}
Accuracy (Test) for sigmoid kernel: 0.675
[[ 8  5]
 [ 8 19]]
              precision    recall  f1-score   support

           0       0.50      0.62      0.55        13
           1       0.79      0.70      0.75        27

    accuracy                           0.68        40
   macro avg       0.65      0.66      0.65        40
weighted avg       0.70      0.68      0.68        40


============================================================

svm sigmoid not normalized

In [ ]:
evaluate_sigmoid_kernel(x_train=x_train_not_normalized, x_test=x_test_not_normalized, y_train=y_train_not_normalized, y_test=y_test_not_normalized)

<h2>SVM (rbf)</h2>

svm rbf normalized

In [13]:
# Define parameter grids for RBF kernel
param_grid_rbf = {'C': C_range, 'gamma': ['scale', 'auto']}

# Function to perform Grid Search and evaluate the model for RBF kernel
def evaluate_rbf_kernel(x_train, y_train, x_test, y_test):

    base_model = SVC(kernel="rbf")
        
    print("Evaluating RBF kernel")
    grid_search = GridSearchCV(base_model, param_grid_rbf, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for RBF kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for RBF kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel  
evaluate_rbf_kernel(x_train=x_train_normalized, y_train=y_train_normalized, x_test=x_test_normalized, y_test=y_test_normalized)

Evaluating RBF kernel
Best parameters for RBF kernel: {'C': 10, 'gamma': 'scale'}
Accuracy (Test) for RBF kernel: 0.6
[[ 8  5]
 [11 16]]
              precision    recall  f1-score   support

           0       0.42      0.62      0.50        13
           1       0.76      0.59      0.67        27

    accuracy                           0.60        40
   macro avg       0.59      0.60      0.58        40
weighted avg       0.65      0.60      0.61        40


============================================================

svm rbf not normalized

In [ ]:
evaluate_rbf_kernel(x_train=x_train_not_normalized, y_train=y_train_not_normalized, x_test=x_test_not_normalized, y_test=y_test_not_normalized)