<h1>Booster - All Features</h1>

In [41]:
import pandas as pd
from sklearn import metrics, svm
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.svm import SVC

In [42]:
import warnings
import numpy as np

# Suppress overflow warning
warnings.filterwarnings("ignore", category=RuntimeWarning)
np.seterr(over='ignore')

{'divide': 'warn', 'over': 'ignore', 'under': 'ignore', 'invalid': 'warn'}

In [43]:
df_normalized = pd.read_csv('normalized_vaccine_data_processed.csv')
df_not_normalized = pd.read_csv('not_normalized_vaccine_data_processed.csv')

In [44]:
df_normalized.head(5)

,Age,Gender,Education,Income,Pregnant,PatientContact,Occupation,CovidPatientCare,EmploymentYears,PreExistingCondition,...,Location_Kuantan,Location_Melaka,Location_Negeri Sembilan,Location_Pahang,Location_Perlis,Location_Pulau Pinang,Location_Sabah,Location_Selangor,Location_Terengganu,AgreeSubsequentBooster
0,0.912281,1,2,1,0,1,1,1,0.742857,0,...,0,0,0,0,0,0,0,0,0,1
1,0.614035,0,4,2,0,1,1,1,0.285714,0,...,0,0,0,0,0,0,0,0,0,1
2,1.000000,1,2,2,0,0,0,0,0.942857,1,...,0,0,0,0,0,0,0,0,0,0
3,0.824561,1,2,1,0,1,1,1,0.628571,0,...,0,0,0,0,0,0,0,0,0,0
4,0.929825,1,2,2,0,1,1,1,0.742857,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
df_not_normalized.head(5)

,Age,Gender,Education,Income,Pregnant,PatientContact,Occupation,CovidPatientCare,EmploymentYears,PreExistingCondition,...,Location_Kuantan,Location_Melaka,Location_Negeri Sembilan,Location_Pahang,Location_Perlis,Location_Pulau Pinang,Location_Sabah,Location_Selangor,Location_Terengganu,AgreeSubsequentBooster
0,52,1,2,1,0,1,1,1,26.0,0,...,0,0,0,0,0,0,0,0,0,1
1,35,0,4,2,0,1,1,1,10.0,0,...,0,0,0,0,0,0,0,0,0,1
2,57,1,2,2,0,0,0,0,33.0,1,...,0,0,0,0,0,0,0,0,0,0
3,47,1,2,1,0,1,1,1,22.0,0,...,0,0,0,0,0,0,0,0,0,0
4,53,1,2,2,0,1,1,1,26.0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
target_normalized = df_normalized['AgreeSubsequentBooster']

target_not_normalized = df_not_normalized['AgreeSubsequentBooster']

features_normalized = df_normalized.drop('AgreeSubsequentBooster', axis=1)

features_not_normalized = df_not_normalized.drop('AgreeSubsequentBooster', axis=1)

In [47]:
print(target_normalized.value_counts())

AgreeSubsequentBooster
1    113
0     86
Name: count, dtype: int64

In [48]:
x_train_normalized, x_test_normalized, y_train_normalized, y_test_normalized = train_test_split(features_normalized, target_normalized, test_size=0.2, random_state=0)

x_train_not_normalized, x_test_not_normalized, y_train_not_normalized, y_test_not_normalized = train_test_split(features_not_normalized, target_not_normalized, test_size=0.2, random_state=0)

<h2>KNN</h2>

KNN normalized

In [49]:
def knn_normalized():
    
    max_accuracy = 0
    max_x = 1


    for x in range(1, 31):

        clf = KNeighborsClassifier(n_neighbors=x)

        scores = cross_val_score(clf, x_train_normalized, y_train_normalized,
                                 cv=5, scoring='accuracy')
        score_mean = scores.mean()
        if score_mean > max_accuracy:
            max_accuracy = score_mean
            max_x = x
        
    print("Best accuracy is ", max_accuracy, " at p = ", max_x)

knn_normalized()

Best accuracy is  0.6977822580645161  at p =  10

In [50]:
# Train the model using the entire training set with the best k
knn_best = KNeighborsClassifier(n_neighbors=20)
knn_best.fit(x_train_normalized, y_train_normalized)

KNeighborsClassifier(n_neighbors=20)

In [51]:
# Predict the target for the test dataset
test_predict = knn_best.predict(x_test_normalized)

test_predict

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [52]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.775

KNN not normalized

In [53]:
def knn_not_normalized():

    max_accuracy = 0
    max_x = 1


    for x in range(1, 31):

        clf = KNeighborsClassifier(n_neighbors=x)

        scores = cross_val_score(clf, x_train_not_normalized, y_train_not_normalized,
                                 cv=5, scoring='accuracy')
        score_mean = scores.mean()
        if score_mean > max_accuracy:
            max_accuracy = score_mean
            max_x = x

    print("Best accuracy is ", max_accuracy, " at p = ", max_x)
    return max_x

best_p = knn_not_normalized()

Best accuracy is  0.7042338709677419  at p =  4

In [54]:
# Train the model using the entire training set with the best k
knn_best = KNeighborsClassifier(n_neighbors=best_p)
knn_best.fit(x_train_not_normalized, y_train_not_normalized)

KNeighborsClassifier(n_neighbors=4)

In [55]:
# Predict the target for the test dataset
test_predict = knn_best.predict(x_test_not_normalized)

test_predict

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [56]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_not_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.5

<h2>Decision tree</h2>

Decision tree normalized

In [57]:
from sklearn.tree import DecisionTreeClassifier


def dt(x_train, y_train):

    # Initialize lists to store depth values and validation scores
    D = []
    validation = []
    scores = {}
    
    # The for loop will test depth values from 3 to 22
    for d in range(3, 23):
        clf = DecisionTreeClassifier(criterion='entropy', max_depth=d, random_state=0)
    
        # Perform cross-validation and compute the mean accuracy
        cv_scores = cross_val_score(clf, x_train, y_train, cv=5, scoring='accuracy')
        validation_score = cv_scores.mean()
    
        # Store depth value and corresponding validation score
        D.append(d)
        validation.append(validation_score)
        scores[d] = validation_score
    
    # Find the best depth
    best_depth = max(scores, key=scores.get)
    print(f"The best depth is {best_depth} with a validation score of {scores[best_depth]}")
    
    return best_depth


best_depth = dt(x_train_normalized, y_train_normalized)

The best depth is 5 with a validation score of 0.7296370967741936

In [58]:
# Train the model using the entire training set with the best depth
dtree_best = DecisionTreeClassifier(criterion='entropy', max_depth=best_depth, random_state=0)
dtree_best.fit(x_train_normalized, y_train_normalized)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)

In [59]:
# Predict the target for the test dataset
test_predict = dtree_best.predict(x_test_normalized)

test_predict

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [60]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.825

decision tree not normalized

In [61]:
best_depth = dt(x_train_not_normalized, y_train_not_normalized)

The best depth is 5 with a validation score of 0.7296370967741936

In [62]:
# Train the model using the entire training set with the best depth
dtree_best = DecisionTreeClassifier(criterion='entropy', max_depth=best_depth, random_state=0)
dtree_best.fit(x_train_not_normalized, y_train_not_normalized)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)

In [63]:
# Predict the target for the test dataset
test_predict = dtree_best.predict(x_test_not_normalized)

test_predict

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [64]:
# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test_not_normalized, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.825

<h2>GNB</h2>

GNB normalized

In [65]:
def gnb_normalized():

    current_model = GaussianNB()
    
    current_model.fit(x_train_normalized, y_train_normalized)
    y_pred = current_model.predict(x_test_normalized)

    acc = metrics.accuracy_score(y_test_normalized, y_pred)
    print("Accuracy (Test):", acc)
        
gnb_normalized()

Accuracy (Test): 0.4

GNB not normalized

In [66]:
def gnb_not_normalized():

    current_model = GaussianNB()
        
    current_model.fit(x_train_not_normalized, y_train_not_normalized)
    test_predict = current_model.predict(x_test_not_normalized)
    print("Accuracy (Test): ", metrics.accuracy_score(y_test_not_normalized, test_predict))
    
gnb_not_normalized()

Accuracy (Test):  0.475

<h2>MNB</h2>

mnb normalized

In [67]:
mnb = MultinomialNB()

scores = cross_val_score(mnb, x_train_normalized, y_train_normalized, cv = 10, scoring="accuracy")
print("Accuracy (Validation) =", scores.mean())
mnb.fit(x_train_normalized, y_train_normalized)
test_predict = mnb.predict(x_test_normalized)
print("Accuracy (Test): ", metrics.accuracy_score(y_test_normalized, test_predict))

Accuracy (Validation) = 0.6783333333333333
Accuracy (Test):  0.775

MNB not normalized

In [68]:
def mnb_not_normalized():
    
    mnb = MultinomialNB()
    
    scores = cross_val_score(mnb, x_train_not_normalized, y_train_not_normalized, cv = 10, scoring="accuracy")
    print("Accuracy (Validation) =", scores.mean())
    mnb.fit(x_train_not_normalized, y_train_not_normalized)
    test_predict = mnb.predict(x_test_not_normalized)
    print("Accuracy (Test): ", metrics.accuracy_score(y_test_not_normalized, test_predict))
    
mnb_not_normalized()

Accuracy (Validation) = 0.7162499999999999
Accuracy (Test):  0.7

<h2>MLP - 1 layer</h2>

MLP 1 layer normalized

In [69]:
# Import necessary libraries
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier

# Function to perform cross-validation and find the best hidden layer size
def find_best_hidden_layer_size(hidden_layer_sizes, x_train, y_train):
    best_score = 0
    best_size = None
    for size in hidden_layer_sizes:
        mlp = MLPClassifier(hidden_layer_sizes=size, max_iter=3000, random_state=42)
        scores = cross_val_score(mlp, x_train, y_train, cv=5, scoring='accuracy')
        mean_score = scores.mean()
        print(f'Hidden layer size {size}: Mean cross-validation accuracy = {mean_score}')
        if mean_score > best_score:
            best_score = mean_score
            best_size = size
    return best_size, best_score

# Define hidden layer sizes to test
hidden_layer_sizes_1 = [(h,) for h in [5] + list(range(10, 101, 5))]
hidden_layer_sizes_2 = [(5, h) for h in [5] + list(range(10, 101, 5))]

# Find the best hidden layer size for 1 hidden layer
best_size_1, best_score_1 = find_best_hidden_layer_size(hidden_layer_sizes_1, x_train_normalized, y_train_normalized)
print(f'Best hidden layer size for 1 layer: {best_size_1} with score {best_score_1}')

Hidden layer size (5,): Mean cross-validation accuracy = 0.6477822580645161
Hidden layer size (10,): Mean cross-validation accuracy = 0.6477822580645161
Hidden layer size (15,): Mean cross-validation accuracy = 0.7040322580645161
Hidden layer size (20,): Mean cross-validation accuracy = 0.6659274193548387
Hidden layer size (25,): Mean cross-validation accuracy = 0.6911290322580645
Hidden layer size (30,): Mean cross-validation accuracy = 0.6725806451612903
Hidden layer size (35,): Mean cross-validation accuracy = 0.6659274193548387
Hidden layer size (40,): Mean cross-validation accuracy = 0.6977822580645161
Hidden layer size (45,): Mean cross-validation accuracy = 0.6977822580645161
Hidden layer size (50,): Mean cross-validation accuracy = 0.7100806451612903
Hidden layer size (55,): Mean cross-validation accuracy = 0.7036290322580645
Hidden layer size (60,): Mean cross-validation accuracy = 0.6663306451612903
Hidden layer size (65,): Mean cross-validation accuracy = 0.6852822580645161
Hidden layer size (70,): Mean cross-validation accuracy = 0.7100806451612903
Hidden layer size (75,): Mean cross-validation accuracy = 0.7100806451612903
Hidden layer size (80,): Mean cross-validation accuracy = 0.6788306451612903
Hidden layer size (85,): Mean cross-validation accuracy = 0.6977822580645161
Hidden layer size (90,): Mean cross-validation accuracy = 0.7038306451612903
Hidden layer size (95,): Mean cross-validation accuracy = 0.6852822580645161
Hidden layer size (100,): Mean cross-validation accuracy = 0.6973790322580645
Best hidden layer size for 1 layer: (50,) with score 0.7100806451612903

MLP 1 layer not normalized

In [70]:
# Find the best hidden layer size for 1 hidden layer
best_size_1, best_score_1 = find_best_hidden_layer_size(hidden_layer_sizes_1, x_train_not_normalized, y_train_not_normalized)
print(f'Best hidden layer size for 1 layer: {best_size_1} with score {best_score_1}')

Hidden layer size (5,): Mean cross-validation accuracy = 0.6223790322580645
Hidden layer size (10,): Mean cross-validation accuracy = 0.6661290322580645
Hidden layer size (15,): Mean cross-validation accuracy = 0.6473790322580645
Hidden layer size (20,): Mean cross-validation accuracy = 0.6663306451612903
Hidden layer size (25,): Mean cross-validation accuracy = 0.6786290322580645
Hidden layer size (30,): Mean cross-validation accuracy = 0.6721774193548387
Hidden layer size (35,): Mean cross-validation accuracy = 0.7106854838709677
Hidden layer size (40,): Mean cross-validation accuracy = 0.6844758064516129
Hidden layer size (45,): Mean cross-validation accuracy = 0.7038306451612903
Hidden layer size (50,): Mean cross-validation accuracy = 0.7036290322580645
Hidden layer size (55,): Mean cross-validation accuracy = 0.7100806451612903
Hidden layer size (60,): Mean cross-validation accuracy = 0.6471774193548387
Hidden layer size (65,): Mean cross-validation accuracy = 0.6911290322580645
Hidden layer size (70,): Mean cross-validation accuracy = 0.7100806451612903
Hidden layer size (75,): Mean cross-validation accuracy = 0.6846774193548387
Hidden layer size (80,): Mean cross-validation accuracy = 0.6909274193548387
Hidden layer size (85,): Mean cross-validation accuracy = 0.6911290322580645
Hidden layer size (90,): Mean cross-validation accuracy = 0.6846774193548387
Hidden layer size (95,): Mean cross-validation accuracy = 0.7288306451612903
Hidden layer size (100,): Mean cross-validation accuracy = 0.6534274193548387
Best hidden layer size for 1 layer: (95,) with score 0.7288306451612903

<h2>MLP - 2 layer</h2>

MLP 2 layer normalized

In [71]:
# Find the best hidden layer size for 2 hidden layers
best_size_2, best_score_2 = find_best_hidden_layer_size(hidden_layer_sizes_2, x_train_normalized, y_train_normalized)
print(f'Best hidden layer size for 2 layers: {best_size_2} with score {best_score_2}')

Hidden layer size (5, 5): Mean cross-validation accuracy = 0.6094758064516129
Hidden layer size (5, 10): Mean cross-validation accuracy = 0.6596774193548387
Hidden layer size (5, 15): Mean cross-validation accuracy = 0.6661290322580645
Hidden layer size (5, 20): Mean cross-validation accuracy = 0.6342741935483871
Hidden layer size (5, 25): Mean cross-validation accuracy = 0.6407258064516129
Hidden layer size (5, 30): Mean cross-validation accuracy = 0.6473790322580645
Hidden layer size (5, 35): Mean cross-validation accuracy = 0.6723790322580645
Hidden layer size (5, 40): Mean cross-validation accuracy = 0.6346774193548387
Hidden layer size (5, 45): Mean cross-validation accuracy = 0.6284274193548387
Hidden layer size (5, 50): Mean cross-validation accuracy = 0.6725806451612903
Hidden layer size (5, 55): Mean cross-validation accuracy = 0.6348790322580645
Hidden layer size (5, 60): Mean cross-validation accuracy = 0.6596774193548387
Hidden layer size (5, 65): Mean cross-validation accuracy = 0.6598790322580645
Hidden layer size (5, 70): Mean cross-validation accuracy = 0.6413306451612903
Hidden layer size (5, 75): Mean cross-validation accuracy = 0.6475806451612903
Hidden layer size (5, 80): Mean cross-validation accuracy = 0.6917338709677419
Hidden layer size (5, 85): Mean cross-validation accuracy = 0.6725806451612903
Hidden layer size (5, 90): Mean cross-validation accuracy = 0.6092741935483871
Hidden layer size (5, 95): Mean cross-validation accuracy = 0.6600806451612903
Hidden layer size (5, 100): Mean cross-validation accuracy = 0.6665322580645161
Best hidden layer size for 2 layers: (5, 80) with score 0.6917338709677419

MLP 2 layer not normalized

In [72]:
# Find the best hidden layer size for 2 hidden layers
best_size_2, best_score_2 = find_best_hidden_layer_size(hidden_layer_sizes_2, x_train_not_normalized, y_train_not_normalized)
print(f'Best hidden layer size for 2 layers: {best_size_2} with score {best_score_2}')

Hidden layer size (5, 5): Mean cross-validation accuracy = 0.6598790322580645
Hidden layer size (5, 10): Mean cross-validation accuracy = 0.6096774193548387
Hidden layer size (5, 15): Mean cross-validation accuracy = 0.6161290322580645
Hidden layer size (5, 20): Mean cross-validation accuracy = 0.6594758064516129
Hidden layer size (5, 25): Mean cross-validation accuracy = 0.6221774193548387
Hidden layer size (5, 30): Mean cross-validation accuracy = 0.6913306451612903
Hidden layer size (5, 35): Mean cross-validation accuracy = 0.5532258064516129
Hidden layer size (5, 40): Mean cross-validation accuracy = 0.6721774193548387
Hidden layer size (5, 45): Mean cross-validation accuracy = 0.603225806451613
Hidden layer size (5, 50): Mean cross-validation accuracy = 0.5653225806451613
Hidden layer size (5, 55): Mean cross-validation accuracy = 0.6096774193548387
Hidden layer size (5, 60): Mean cross-validation accuracy = 0.6786290322580645
Hidden layer size (5, 65): Mean cross-validation accuracy = 0.5840725806451613
Hidden layer size (5, 70): Mean cross-validation accuracy = 0.6157258064516129
Hidden layer size (5, 75): Mean cross-validation accuracy = 0.6235887096774194
Hidden layer size (5, 80): Mean cross-validation accuracy = 0.6725806451612903
Hidden layer size (5, 85): Mean cross-validation accuracy = 0.7040322580645161
Hidden layer size (5, 90): Mean cross-validation accuracy = 0.6917338709677419
Hidden layer size (5, 95): Mean cross-validation accuracy = 0.4905241935483871
Hidden layer size (5, 100): Mean cross-validation accuracy = 0.6534274193548387
Best hidden layer size for 2 layers: (5, 85) with score 0.7040322580645161

<h2>SVM (linear)</h2>

SVM normalized

In [73]:
from sklearn.model_selection import GridSearchCV

# Define the parameter range for C
C_range = [0.1,1,10,100]
degree = [2,3,4]

param_grid_linear = {'C': C_range}

# Function to perform Grid Search and evaluate the model for linear kernel
def evaluate_linear_kernel(x_train, y_train, x_test, y_test):
    print("Evaluating linear kernel")
    grid_search = GridSearchCV(SVC(kernel='linear'), param_grid_linear, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for linear kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for linear kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel    
evaluate_linear_kernel(x_train_normalized, y_train_normalized, x_test_normalized, y_test_normalized)

Evaluating linear kernel
Best parameters for linear kernel: {'C': 0.1}
Accuracy (Test) for linear kernel: 0.725
[[ 9  4]
 [ 7 20]]
              precision    recall  f1-score   support

           0       0.56      0.69      0.62        13
           1       0.83      0.74      0.78        27

    accuracy                           0.72        40
   macro avg       0.70      0.72      0.70        40
weighted avg       0.75      0.72      0.73        40


============================================================

SVM not normalized

In [74]:
C_range = [0.01,0.1,1,10,100]

param_grid_linear = {'C': C_range}

def evaluate_linear_kernel():

    estimator = SVC(kernel='linear') 
    param_grid = param_grid_linear

    grid_search = GridSearchCV(estimator, param_grid, cv=10, scoring='accuracy')
    grid_result = grid_search.fit(x_train_not_normalized, y_train_not_normalized)

    print(f"Best parameters for {type(estimator).__name__}: {grid_result.best_params_}")

    best_model = grid_result.best_estimator_

    test_predict = best_model.predict(x_test_not_normalized)

    accuracy = metrics.accuracy_score(y_test_not_normalized, test_predict)
    print(f"Accuracy (Test) for best model: {accuracy:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test_not_normalized, test_predict))
    print("\nClassification Report:")
    print(classification_report(y_test_not_normalized, test_predict))
    print("\n" + "="*60 + "\n")

    return accuracy
  
evaluate_linear_kernel()

Best parameters for SVC: {'C': 0.01}
Accuracy (Test) for best model: 0.7000

Confusion Matrix:
[[ 8  5]
 [ 7 20]]

Classification Report:
              precision    recall  f1-score   support

           0       0.53      0.62      0.57        13
           1       0.80      0.74      0.77        27

    accuracy                           0.70        40
   macro avg       0.67      0.68      0.67        40
weighted avg       0.71      0.70      0.70        40


============================================================

0.7

<h2>SVM (polynomial)</h2>

SVM Polynomial normalized

In [75]:
degree = [2,3,4]
# Define parameter grids for polynomial kernel
param_grid_poly = {'C': [0.1,1,10,100], 'degree': degree, 'gamma': ['scale', 'auto']}

# Function to perform Grid Search and evaluate the model for polynomial kernel
def evaluate_poly_kernel(x_train, y_train, x_test, y_test):

    base_model = SVC(kernel="poly")
        
    print("Evaluating polynomial kernel")
    grid_search = GridSearchCV(base_model, param_grid_poly, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for polynomial kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for polynomial kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel  
evaluate_poly_kernel(x_train=x_train_normalized, y_train=y_train_normalized, x_test=x_test_normalized, y_test=y_test_normalized)

Evaluating polynomial kernel
Best parameters for polynomial kernel: {'C': 1, 'degree': 2, 'gamma': 'scale'}
Accuracy (Test) for polynomial kernel: 0.775
[[10  3]
 [ 6 21]]
              precision    recall  f1-score   support

           0       0.62      0.77      0.69        13
           1       0.88      0.78      0.82        27

    accuracy                           0.78        40
   macro avg       0.75      0.77      0.76        40
weighted avg       0.79      0.78      0.78        40


============================================================

SVM polynomial not normalized

In [76]:
#print the best evaluate linear kernel  
evaluate_poly_kernel(x_train=x_train_normalized, y_train=y_train_normalized, x_test=x_test_normalized, y_test=y_test_normalized)

Evaluating polynomial kernel
Best parameters for polynomial kernel: {'C': 1, 'degree': 2, 'gamma': 'scale'}
Accuracy (Test) for polynomial kernel: 0.775
[[10  3]
 [ 6 21]]
              precision    recall  f1-score   support

           0       0.62      0.77      0.69        13
           1       0.88      0.78      0.82        27

    accuracy                           0.78        40
   macro avg       0.75      0.77      0.76        40
weighted avg       0.79      0.78      0.78        40


============================================================

<h2>SVM (sigmoid)</h2>

svm sigmoid normalized

In [77]:
# Define parameter grids for sigmoid kernel
param_grid_sigmoid = {'C': C_range, 'gamma': ['scale', 'auto']}

# Function to perform Grid Search and evaluate the model for sigmoid kernel
def evaluate_sigmoid_kernel(x_train, y_train, x_test, y_test):
    
    base_model = SVC(kernel="sigmoid")
        
    print("Evaluating sigmoid kernel")
    grid_search = GridSearchCV(base_model, param_grid_sigmoid, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for sigmoid kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for sigmoid kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel  
evaluate_sigmoid_kernel(x_train=x_train_normalized, x_test=x_test_normalized, y_train=y_train_normalized, y_test=y_test_normalized)

Evaluating sigmoid kernel
Best parameters for sigmoid kernel: {'C': 1, 'gamma': 'scale'}
Accuracy (Test) for sigmoid kernel: 0.675
[[10  3]
 [10 17]]
              precision    recall  f1-score   support

           0       0.50      0.77      0.61        13
           1       0.85      0.63      0.72        27

    accuracy                           0.68        40
   macro avg       0.68      0.70      0.66        40
weighted avg       0.74      0.68      0.69        40


============================================================

svm sigmoid not normalized

In [78]:
evaluate_sigmoid_kernel(x_train=x_train_not_normalized, x_test=x_test_not_normalized, y_train=y_train_not_normalized, y_test=y_test_not_normalized)

Evaluating sigmoid kernel
Best parameters for sigmoid kernel: {'C': 1, 'gamma': 'auto'}
Accuracy (Test) for sigmoid kernel: 0.675
[[ 0 13]
 [ 0 27]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        13
           1       0.68      1.00      0.81        27

    accuracy                           0.68        40
   macro avg       0.34      0.50      0.40        40
weighted avg       0.46      0.68      0.54        40


============================================================

/opt/anaconda3/envs/code/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/code/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/code/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

<h2>SVM (rbf)</h2>

svm rbf normalized

In [79]:
# Define parameter grids for RBF kernel
param_grid_rbf = {'C': C_range, 'gamma': ['scale', 'auto']}

# Function to perform Grid Search and evaluate the model for RBF kernel
def evaluate_rbf_kernel(x_train, y_train, x_test, y_test):

    base_model = SVC(kernel="rbf")
        
    print("Evaluating RBF kernel")
    grid_search = GridSearchCV(base_model, param_grid_rbf, cv=5, scoring='accuracy')
    grid_result = grid_search.fit(x_train, y_train)
    print(f"Best parameters for RBF kernel: {grid_result.best_params_}")

    # Train the model with the best parameters
    best_model = grid_result.best_estimator_
    best_model.fit(x_train, y_train)

    # Predict on the test set
    test_predict = best_model.predict(x_test)

    # Compute and print the model accuracy on the test set
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f"Accuracy (Test) for RBF kernel: {accuracy}")

    # Print confusion matrix and classification report
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))
    print("\n" + "="*60 + "\n")

#print the best evaluate linear kernel  
evaluate_rbf_kernel(x_train=x_train_normalized, y_train=y_train_normalized, x_test=x_test_normalized, y_test=y_test_normalized)

Evaluating RBF kernel
Best parameters for RBF kernel: {'C': 10, 'gamma': 'scale'}
Accuracy (Test) for RBF kernel: 0.825
[[11  2]
 [ 5 22]]
              precision    recall  f1-score   support

           0       0.69      0.85      0.76        13
           1       0.92      0.81      0.86        27

    accuracy                           0.82        40
   macro avg       0.80      0.83      0.81        40
weighted avg       0.84      0.82      0.83        40


============================================================

svm rbf not normalized

In [80]:
evaluate_rbf_kernel(x_train=x_train_not_normalized, y_train=y_train_not_normalized, x_test=x_test_not_normalized, y_test=y_test_not_normalized)

Evaluating RBF kernel
Best parameters for RBF kernel: {'C': 1, 'gamma': 'auto'}
Accuracy (Test) for RBF kernel: 0.625
[[ 9  4]
 [11 16]]
              precision    recall  f1-score   support

           0       0.45      0.69      0.55        13
           1       0.80      0.59      0.68        27

    accuracy                           0.62        40
   macro avg       0.62      0.64      0.61        40
weighted avg       0.69      0.62      0.64        40


============================================================